<?php

// @codingStandardsIgnoreFile
use Magento\Catalog\Model\Product\Option;

/**
 * @var \SD\CustomOptionDefaultValue\Block\Product\View\Options\Type\Select\Checkable $block
 */
$option = $block->getOption();
if ($option) : ?>
    <?php
    $configValue = $block->getPreconfiguredValue($option);
    $optionType = $option->getType();
    $arraySign = $optionType === Option::OPTION_TYPE_CHECKBOX ? '[]' : '';
    $count = 1;
    ?>
<?php
$product = $block->getProduct();
$basePrice = $product ? $product->getFinalPrice() : null;
?>
<div class="options-list nested" id="options-<?php echo /* @noEscape */ $option->getId() ?>-list">
    <?php if ($optionType === Option::OPTION_TYPE_RADIO && !$option->getIsRequire()): ?>
    <div class="field choice admin__field admin__field-option">
        <input type="radio"
               id="options_<?php echo /* @noEscape */
               $option->getId() ?>"
               class="radio admin__control-radio product-custom-option"
               name="options[<?php echo /* @noEscape */
               $option->getId() ?>]"
               data-selector="options[<?php echo /* @noEscape */
               $option->getId() ?>]"
               onclick="<?php echo $block->getSkipJsReloadPrice() ? '' : 'opConfig.reloadPrice()' ?>"
               value=""
               checked="checked"
        />
        <label class="label admin__field-label" for="options_<?php echo /* @noEscape */
        $option->getId() ?>">
                        <span>
                            <?php echo /* @noEscape */
                            __('None') ?>
                        </span>
        </label>
    </div>
<?php endif; ?>

    <?php foreach ($option->getValues() as $value) : ?>
        <?php
        $checked = '';
        $count++;
        if ($arraySign) {
            $checked = is_array($configValue) && in_array($value->getOptionTypeId(), $configValue) ? 'checked' : '';
        } else {
            $checked = $configValue == $value->getOptionTypeId() ? 'checked' : '';
        }

        if (!$configValue && $value->getData('is_default')) {
            $checked = 'checked';
        }

        $dataSelector = 'options[' . $option->getId() . ']';
        if ($arraySign) {
            $dataSelector .= '[' . $value->getOptionTypeId() . ']';
        }
        ?>

        <div class="field choice admin__field admin__field-option <?php echo /* @noEscape */
        $option->getIsRequire() ? 'required' : '' ?>">
            <input type="<?php echo /* @noEscape */
            $optionType ?>"
                   class="<?php /** @noinspection DisconnectedForeachInstructionInspection */
                   echo /* @noEscape */
                   $optionType === Option::OPTION_TYPE_RADIO ?
                       'radio admin__control-radio' :
                       'checkbox admin__control-checkbox' ?> <?php echo /* @noEscape */
                   $option->getIsRequire() ? 'required' : '' ?>
                       product-custom-option
                        <?php echo $block->getSkipJsReloadPrice() ? '' : 'opConfig.reloadPrice()' ?>"
                   name="options[<?php echo $option->getId() ?>]<?php echo /* @noEscape */
                   $arraySign ?>"
                   id="options_<?php echo /* @noEscape */
                       $option->getId() . '_' . $count ?>"
                   value="<?php echo /* @noEscape */
                   $value->getOptionTypeId() ?>"
                <?php echo /* @noEscape */
                $checked ?>
                   data-selector="<?php echo /* @noEscape */
                   $dataSelector ?>"
                   price="<?php echo /* @noEscape */
                   $block->getCurrencyByStore($value) ?>"
            />
            <label class="label admin__field-label"
                   for="options_<?php echo /* @noEscape */
                       $option->getId() . '_' . $count ?>">
                <span>
                    <?php echo $block->escapeHtml($value->getTitle()) ?>
                </span>
                 <div class="additional-info">
                    <?php if($value->getSku()) { ?>
                 <span class="option-sku">
                    <?= $block->escapeHtml($value->getSku()) ?>
                </span>
                <?php } ?>
                <?php if ($checked AND empty($value->getPrice()) ) {
                        $formattedOptionValue = is_numeric($basePrice) ? number_format($basePrice, 2, '.', '') : $basePrice;
                 ?>
                    <span class="price-notice">
                        <span class="price-container tax weee">
                            <span data-price-amount="<?= /* @noEscape */ $formattedOptionValue; ?>" data-price-type="" class="price-wrapper "> $<?= /* @noEscape */ $formattedOptionValue; ?> </span>
                            </span>
                        </span>
                                        
                <?php } else { ?>
                    <?= /* @noEscape */ $block->formatPrice($value) ?>
                <?php } ?>

                <?php if($value->getData('extra_info')) { ?>
                 <span class="option-extra-info">
                    <?= $block->escapeHtml($value->getData('extra_info')) ?>
                </span>
                <?php } ?>
                </div>
            </label>
        </div>
    <?php endforeach; ?>
    </div>
<?php endif; ?>


<script>
    require(['jquery'], function($) {
        $(document).ready(function() {
            function updateSelectedText() {
                var selectedTexts = [];
                var selected_option_sku = '';

                $('.product-custom-option').each(function() {
                    var $input = $(this);

                    // For radio buttons: only include the checked one
                    if ($input.is(':radio') && $input.prop('checked')) {
                        var labelText = $input.closest('.admin__field-option').find('label span:first').text().trim();
                        var extraText = $input.closest('.admin__field-option').find('span.option-extra-info').text().trim();
                        selected_option_sku = $input.closest('.admin__field-option').find('span.option-sku').text().trim();
                        selectedTexts.push(labelText+' '+extraText);
                    }

                    // For checkboxes: include all checked
                    if ($input.is(':checkbox') && $input.prop('checked')) {
                        var labelText = $input.closest('.admin__field-option').find('label span:first').text().trim();
                        var extraText = $input.closest('.admin__field-option').find('span.option-extra-info').text().trim();
                        selected_option_sku = $input.closest('.admin__field-option').find('span.option-sku').text().trim();
                        selectedTexts.push(labelText+' '+extraText);
                    }
                });

                $('.selected-options-txt').text(' : '+selectedTexts.join(', '));
                $('.p_sku_value')
                .css('background-color', '#ed8faf30') // light yellow
                .text(selected_option_sku)
                .animate({ backgroundColor: '#ffffff' }, 1000); // fade back to white

                
            }

            // Bind change event to inputs
            $('.product-custom-option').on('change', function() {
                updateSelectedText();

            });

            // Trigger on page load to capture default checked options
            updateSelectedText();
        });
    });
</script>